name: "doc-kurento"

on:
  # Manual trigger.
  workflow_dispatch:
    inputs:
      jobRelease:
        description: "jobRelease: Enable to build release versions; disable for development builds"
        required: false
        type: "boolean"
        default: false
      runnerGroup:
        description: "runnerGroup: Set of runners where the workflow jobs should be run"
        required: false
        type: "string"
        default: "Linux"

defaults:
  run:
    shell: "bash --noprofile --norc -o errexit -o errtrace -o pipefail -o nounset -o xtrace {0}"

jobs:
  build:
    runs-on: ["self-hosted", "${{ inputs.runnerGroup }}"]
    timeout-minutes: 30
    steps:
      # Action: https://github.com/actions/checkout
      - name: "Checkout"
        uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1

      - name: "Configure the environment for ci-scripts/"
        working-directory: "ci-scripts/"
        run: |
          echo "$PWD" >>$GITHUB_PATH
          echo "CI_SCRIPTS_PATH=$PWD" >>$GITHUB_ENV
          echo "JOB_TIMESTAMP=$(date --utc +%Y%m%d%H%M%S)" >>$GITHUB_ENV

      - name: "Configure the environment for job script"
        run: |
          # Env vars used by `ci_job_deploy_doc.sh`.
          echo "ENV_PATH=$GITHUB_ENV" >>$GITHUB_ENV

          # Commit that triggered this build. Used by `doc_deploy.sh`.
          echo "GIT_HASH_SHORT=${GITHUB_SHA:0:7}" >>$GITHUB_ENV

          # Path to the SSH key. Used by `doc_deploy.sh`.
          # Note: No need to clean, $RUNNER_TEMP/ is deleted after each run.
          GIT_SSH_KEY_PATH="$RUNNER_TEMP/id_git_ssh"
          echo "GIT_SSH_KEY_PATH=$GIT_SSH_KEY_PATH" >>$GITHUB_ENV
          echo "${{ secrets.KURENTOCI_PRIVATE_SSH_KEY }}" >"$GIT_SSH_KEY_PATH"
          chmod 0400 "$GIT_SSH_KEY_PATH"

          # Path to the Maven settings.xml file.
          echo "MAVEN_SETTINGS_PATH=$GITHUB_WORKSPACE/clients/java/maven-settings/settings.xml" >>$GITHUB_ENV

          # Env vars used by the Maven settings.xml file.
          echo "KURENTO_MAVEN_DOWNLOAD_USERNAME=${{ secrets.KURENTO_MAVEN_DOWNLOAD_USERNAME }}" >>$GITHUB_ENV
          echo "KURENTO_MAVEN_DOWNLOAD_PASSWORD=${{ secrets.KURENTO_MAVEN_DOWNLOAD_PASSWORD }}" >>$GITHUB_ENV

      - name: "Run job script"
        env:
          JOB_RELEASE: "${{ inputs.jobRelease }}"
        run: "ci_job_deploy_doc.sh"
